---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helm-repository-grafana.yaml
- helm-release-grafana.yaml
- secrets.yaml

configMapGenerator:
- name: grafana-default-config
  namespace: monitoring
  files:
  - conf.d/grafana-ini.yaml

configurations:
- name-reference.yaml
