---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: modules
  namespace: flux-system
spec:
  path: ./after/modules
  postBuild:
    substitute:
      secret_store: after-store
      domain_name: after.example.com
  sourceRef:
    kind: GitRepository
    name: test-source
    namespace: flux-system
  wait: false
