---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-release
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      interval: 24h0m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-repository
        namespace: flux-system
      version: 10.0.0
  releaseName: grafana
  targetNamespace: monitoring

  valuesFrom:
  - kind: ConfigMap
    name: grafana-default-config
    valuesKey: grafana-ini.yaml
    optional: false

  values:
    admin:
      existingSecret: grafana-admin-credentials
      userKey: username
      passwordKey: password

    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: grafana.${domain_name}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
      - grafana.${domain_name}
      path: /
      pathType: Prefix
      tls: []

    persistence:
      enabled: false
