---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  data:
  - secretKey: username
    remoteRef:
      key: grafana_username
  - secretKey: password
    remoteRef:
      key: grafana_password
  refreshInterval: 24h
  secretStoreRef:
    name: ${secret_store}
    kind: ClusterSecretStore
