---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: modules
  namespace: flux-system
spec:
  interval: 15m0s
  path: ../modules
  postBuild:
    substitute:
      secret_store: before-store
      domain_name: before.example.com
  sourceRef:
    kind: GitRepository
    name: test-source
    namespace: flux-system
  timeout: 2m0s
  wait: false
