---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: modules
  namespace: flux-system
spec:
  path: ./ci/test-data/flux-diff/before/modules
  postBuild:
    substitute:
      secret_store: before-store
      domain_name: before.example.com
  sourceRef:
    kind: GitRepository
    name: test-source
    namespace: flux-system
  wait: false
